services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mao-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mao-admin-panel
    depends_on:
      - mongo
    networks:
      - mao-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mao-network

networks:
  mao-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local 